sudo: required
dist: trusty
language: generic 
compiler:
  - gcc
notifications:
  email:
    recipients:
       - rohit517@terpmail.umd.edu

env:
  matrix:
    - ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  - gem install coveralls-lcov
script: 
  - source .ci_config/travis.sh
